name: motorgarage
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  permission_handler: ^5.0.0+hotfix.3
  font_awesome_flutter: any
  flutter_form_builder: ^3.13.5
  flutter_custom_clippers: ^1.1.0
  cached_network_image: ^2.0.0
  email_validator: '^1.0.0'
  file_utils: ^0.1.4
  fluttertoast: ^4.0.1
  dio: ^3.0.9
  mime: ^0.9.6+3
  flutter_local_notifications: ^1.4.2
  progress_dialog: ^1.2.0
  datetime_picker_formfield: ^1.0.0
  url_launcher: ^5.4.2
  carousel_slider: ^1.4.1
  chewie: ^0.12.2
  video_player: ^1.0.1
  curved_navigation_bar: ^0.3.7
  flutter_icons: ^1.1.0
  hexcolor: ^2.0.0
  country_pickers: ^1.3.0
  flutter_typeahead: ^1.8.8
  flutter_chips_input: ^1.9.4
  bottom_navy_bar: ^5.5.0
  validators: ^2.0.1
  date_range_picker: ^1.0.6
  firebase_core: ^0.4.0+9
  firebase_database: ^3.1.1
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.3
  firebase_analytics: ^5.0.2
  provider: 2.0.1
  intro_slider: ^2.3.4
  google_maps_flutter: ^1.2.0
  geolocator: ^6.1.7
  geocoder: ^0.2.1
  google_sign_in: ^4.1.1
  expansion_card: ^0.1.0
  flutter_rating_bar: ^3.2.0
  expansion_tile_card: ^1.1.0
  firebase_messaging: ^6.0.1
  typicons_flutter: ^0.5.0
  google_fonts: ^1.1.2
  web_scraper: ^0.0.6
  webview_flutter: ^2.0.12
  tflite: 

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - lib/assets/video1.mp4
   - lib/assets/ayurveda.png
   - lib/assets/cardiology.png
   - lib/assets/doctor.png
   - lib/assets/neurologist.png
   - lib/assets/radiologist.png
   - lib/assets/homeopathy.png
   - lib/assets/gynecologist.png
   - lib/assets/dental-care.png
   - lib/assets/dermatology.png
   - lib/assets/physician.png
   - lib/assets/discount.png
   - lib/assets/login.jpg
   - lib/assets/grey.jpg
   - lib/assets/pediatric.jpg
   - lib/assets/orthopedic.jpg
   - lib/assets/greenbg.png
   - lib/assets/pinkbg.png
   - lib/assets/promise.png
   - lib/assets/expert.png
   - lib/assets/logo.png
   - lib/assets/feedback.png
   - lib/assets/faqs.png
   - lib/assets/contactus.jpg
   - lib/assets/getin.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CreteRound     
      fonts:
        - asset: lib/assets/creteround_regular.ttf
    - family: Lobster     
      fonts:
        - asset: lib/assets/lobster_regular.ttf
    - family: PermanentMarker     
      fonts:
        - asset: lib/assets/permanentmarker.ttf
    - family: satisfy     
      fonts:
        - asset: lib/assets/satisfy_regular.ttf
    
  
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
